pub mod alternative_me_tests;
pub mod bitdis_tests;
pub mod cbbi_tests;
pub mod coin_gecko_tests;
pub mod price_change_tests;
pub mod quiet_mode_tests;
pub mod cache_tests;
pub mod config_tests;
pub mod notifier_tests;
